### ISSUE TITLE
Assert when using JqGroupBegin nested inside a task

### ISSUE THREAD

**Issue by DaviesLeigh** [jonasmr/jq#1]
I'm hitting an assert in JqGroupBegin on the line
JQ_ASSERT(Job.Parent == Parent);
This happens when i'm start using JqGroupBegin from inside another task.
I believe it just needs changing to
JQ_ASSERT(Job.Parent == (Parent % JQ_JOB_BUFFER_SIZE));
The assert is firing when the Parent has exceeded the buffer size while the Job.Parent appears to be modulus the the Parent handle been checked against.

**Comment by jonasmr** [comment]
Hi.
Thank you for the report - you are correct.
I've added a fix, and also changed it so NextHandle starts at JQ_JOB_BUFFER_SIZE, so bugs like these occur immediately.
